/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gobang_JNIAdapter */

#ifndef _Included_gobang_JNIAdapter
#define _Included_gobang_JNIAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gobang_JNIAdapter
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gobang_JNIAdapter_reset
  (JNIEnv *, jobject);

/*
 * Class:     gobang_JNIAdapter
 * Method:    generateChessInfo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gobang_JNIAdapter_generateChessInfo
  (JNIEnv *, jobject);

/*
 * Class:     gobang_JNIAdapter
 * Method:    playChess
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gobang_JNIAdapter_playChess
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
